name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi httpx pytest flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Verify `TestClient` import source
      run: |
        # Ensure TestClient is imported from fastapi.testclient
        if ! grep -q "from fastapi.testclient import TestClient" main_test.py; then
          echo "TestClient must be imported from fastapi.testclient" && exit 1
        fi

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat other errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      env:
        PYTHONPATH: .
      run: |
        pytest --maxfail=3 --disable-warnings
